### ISSUE TITLE
3.6.1 dapi-test-pod.yaml 文件格式错误

### ISSUE THREAD

**Issue by achuDk** [kubeguide/K8sDefinitiveGuide-V4-Sourcecode#1]
使用 ”K8sDefinitiveGuide-V4-Sourcecode/Chapter3/3.6.1 dapi-test-pod.yaml“ 该sample创建pod时报错，原因为 “3.6.1 dapi-test-pod.yaml” 这个文件中从第8行到第22行缺少缩进。

**Comment by jiaxinonly** [comment]
对的，源代码和书上的不一致！

**Comment by kubeguide** [comment]
已更正，感谢指正！
