### ISSUE TITLE
4.3.2 headless-service-cassandra.yaml 失败了

### ISSUE THREAD

**Issue by Inuyasha-Monster** [kubeguide/K8sDefinitiveGuide-V4-Sourcecode#10]
![image](https://user-images.githubusercontent.com/12888788/94338027-b1b0b200-0021-11eb-8135-01d3e1a3e523.png)
![image](https://user-images.githubusercontent.com/12888788/94338039-cd1bbd00-0021-11eb-9d90-c6b727e29f57.png)
![image](https://user-images.githubusercontent.com/12888788/94338046-e6bd0480-0021-11eb-90b8-e1d23aa5c5fe.png)
进入容器当中访问kubernetes的api失败

**Comment by kubeguide** [comment]
DNS配置可能有问题，在UnknownHostException中的服务名是 kubernetes.default.cluster.local，是不正确的
正确的服务名应该是kubernetes.default.svc.cluster.local
