### ISSUE TITLE
dapi-test-pod-volume.yaml --- There is no permission to mount /etc here

### ISSUE THREAD

**Issue by MiLeskylimit** [kubeguide/K8sDefinitiveGuide-V4-Sourcecode#12]
There is no permission to mount /etc here
mounting "/var/lib/docker/containers/b171519964504fc15d337ca9b3b2eeb85dbbd5a9a012e88c496ee35ac0e11521/resolv.conf" to rootfs at "/var/lib/docker/overlay2/2fb37caa0b2007be127265ffede8ad983c807c56c742af3edf62491f5c7eae98/merged/etc/resolv.conf" caused: open /var/lib/docker/overlay2/2fb37caa0b2007be127265ffede8ad983c807c56c742af3edf62491f5c7eae98/merged/etc/resolv.conf: read-only file system: unknown

**Comment by kubeguide** [comment]
已修订，感谢指正！
