### ISSUE TITLE
cm-test-pod-envfrom.yaml 问题

### ISSUE THREAD

**Issue by stupidcupid** [kubeguide/K8sDefinitiveGuide-V4-Sourcecode#13]
apiVersion: v1
kind: Pod
metadata:
  name: cm-test-pod
spec:
  containers:
  - name: cm-test
    image: busybox
    command: [ "/bin/sh", "-c", "env" ]
    envFrom:
    - configMapRef:
       name: cm-appvars
  restartPolicy: Never

configMapRef 缺少分号

**Comment by kubeguide** [comment]
代码是完整的，没有缺少分号
