### ISSUE TITLE
prometheus-grafana.yaml 文件内容有问题

### ISSUE THREAD

**Issue by Devin6Tam** [kubeguide/K8sDefinitiveGuide-V4-Sourcecode#2]
![image](https://user-images.githubusercontent.com/16789601/61509864-1e461f00-aa23-11e9-9562-176036bd565b.png)   
![image](https://user-images.githubusercontent.com/16789601/61509902-42a1fb80-aa23-11e9-8441-e400792d586a.png)

**Comment by kubeguide** [comment]
文件内容是没问题的。
查看日志的命令需要指定容器名称，语法如下：
kubectl logs <pod-name> -c <container-name>
