### ISSUE TITLE
日志收集-fluentd 无法连接到 se, kubernetes1.14 版本中 se 需要权限访问apiserver

### ISSUE THREAD

**Issue by lucian521** [kubeguide/K8sDefinitiveGuide-V4-Sourcecode#4]
fluentd 日志：

error="Can not reach Elasticsearch cluster ({:host=>\"elasticsearch-logging\",
 :port=>9200, :scheme=>\"http\"})! getaddrinfo: 
 Name or service not known (SocketError)" plugin_id="object:1384fa4"

elaticsearch 日志：

 Error finding endpoints: endpoints "elasticsearch-logging" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "endpoints" in API group "" in the namespace "kube-system
 
 
问下作者 demo 有没有测试过，

**Comment by kubeguide** [comment]
应该跟RBAC配置相关，默认情况下不会特别针对 User "system:serviceaccount:kube-system:default" 有权限限制
可以先在kube-apiserver关闭RBAC授权模式，然后测试elasticsearch应用。
