### ISSUE TITLE
Heketi设置ClusterFS集群报错

### ISSUE THREAD

**Issue by ghost** [kubeguide/K8sDefinitiveGuide-V4-Sourcecode#5]
您好！
请问一下书上第532页的这两条命令是在节点上执行还是在Heketi容器中执行？
export HEKETI_CLI_SERVER=http://localhost:8080
heketi-cli topology load --json=topology.json
我是在容器中执行，但是报如下错误：
Creating cluster ... ID: be9747c4a4897cd473ae58ddf7e0536d
        Allowing file volumes on cluster.
        Allowing block volumes on cluster.
        Creating node node1 ... Unable to create node: New Node doesn't have glusterd running
        Creating node node1 ... Unable to create node: New Node doesn't have glusterd running
        Creating node node3 ... Unable to create node: New Node doesn't have glusterd running
我的三个Node都安装并运行了glusterd程序了。

**Comment by ghost** [comment]
已解决

**Comment by ghost** [comment]
教材有问题，只建了ServiceAccount，没有授权。

**Comment by wxdb** [comment]
请问如何解决的 ？

**Comment by ghost** [comment]
没有为创建的ServiceAccount授权，所以没法操作，请参考：
https://blog.csdn.net/q1403539144/article/details/86566796
